# Based on templates from:
# https://github.com/hoo-dles/morphe-patches
# Modified for this repository.
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please check the [existing app requests](https://github.com/rushiranpise/morphe-patches/discussions/categories/app-requests) first. If a discussion is already open, upvote it for visibility! :arrow_up:
        <br />
  - type: input
    id: app_name
    attributes:
      label: App Name
      description: Full name of the app as shown on Play Store
      placeholder: Really Cool App
    validations:
      required: true

  - type: input
    id: package_name
    attributes:
      label: Package Name
      description: "Official android package name"
      placeholder: com.reallycool.app
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Requested Features
      description: List the specific features you would like patched on this app
      placeholder: |
        - Unlock premium
        - Remove ads
        - Block telemetry
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: Any other details that may be helpful to patch development
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have verified that a suitable patch does not already exist on another [community repo](https://Morphe-patches.software).
          required: true
        - label: I understand that server-side features (AI, cloud sync) cannot be patched.
          required: true
        - label: This app request is not for bypassing a region-lock (use a VPN).
          required: true