package app.template.patches.boldvoice

import app.morphe.patcher.patch.PatchException
import app.morphe.patcher.patch.rawResourcePatch
import app.template.patches.shared.Constants.BOLDVOICE_COMPATIBILITY
import java.security.MessageDigest

/**
 * BoldVoice premium unlock — Hermes bytecode patch (HBC v96).
 * AUTO-GENERATED by tools/boldvoice_update.py — do not edit manually.
 *
 * Source APK : boldvoice_4.6.6.apks
 * Version    : ? (versionCode=?)
 * Bundle SHA : 1603f2ef06af7b8c19b69be20918c23ec209244c
 *
 * 16 patch sites:
 *    1. isSubscriber selector
 *    2. isProSubscriber selector
 *    3. subStatus selector
 *    4. state update isSubscriber read
 *    5. state update isProSubscriber read
 *    6. state update subStatus read
 *    7. state update subscriptionData truthy
 *    8. navigation gate
 *    9. hasActiveEntitlementOrSubscription
 *   10. hasActiveEntitlements
 *   11. useUpgradeToSuper return false
 *   12. GenerativeUpsellInterstice upsell card
 *   13. show paywall screen action
 *   14. showPaywallScreen selector
 *   15. ForceUpdateScreen no-op
 *   16. presentSuperwall bypass
 *
 * HBC v96 opcodes: 0x5C=Ret  0x73=LoadConstString  0x76=LoadConstUndefined(nop)
 *                          0x78=LoadConstTrue  0x79=LoadConstFalse
 */
@Suppress("unused")
val boldVoiceUnlockPremiumPatch = rawResourcePatch(
    name = "Unlock Premium",
    description = "Unlocks BoldVoice premium subscription and removes upsell nags.",
    default = true
) {
    compatibleWith(BOLDVOICE_COMPATIBILITY)

    execute {
        val bundlePath = "assets/index.android.bundle"
        val bundle = get(bundlePath)
        if (!bundle.exists()) throw PatchException("$bundlePath not found.")

        val bytes = bundle.readBytes()
        bytes.requireHermes(bundlePath)

        bytes.replaceUnique(
            "isSubscriber selector",
            hex("6C 00 01 36 00 00 01 F8 37 00 00 02 6C F5"),
            hex("78 00 5C 00 76 00 76 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "isProSubscriber selector",
            hex("6C 00 01 36 00 00 01 F8 37 00 00 02 E0 F4"),
            hex("78 00 5C 00 76 00 76 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "subStatus selector",
            hex("6C 00 01 36 00 00 01 F8 37 00 00 02 BC 7D"),
            hex("73 00 7A 4E 5C 00 76 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "state update isSubscriber read",
            hex("37 12 1F 0B 6C F5"),
            hex("78 12 76 00 76 00")
        )

        bytes.replaceUnique(
            "state update isProSubscriber read",
            hex("37 11 1F 0C E0 F4"),
            hex("78 11 76 00 76 00")
        )

        bytes.replaceUnique(
            "state update subStatus read",
            hex("37 10 1F 0D BC 7D"),
            hex("73 10 7A 4E 76 00")
        )

        bytes.replaceUnique(
            "state update subscriptionData truthy",
            hex("37 13 1F 0A 77 9F"),
            hex("78 13 76 00 76 00")
        )

        bytes.replaceUnique(
            "navigation gate",
            hex("29 01 00 2E 03 01 02 29 00 01 2E 04 00 00 2E 02 00 01 6E 00 0C 49 02 02"),
            hex("76 00 5C 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "hasActiveEntitlementOrSubscription",
            hex("6C 01 01 37 00 01 01 19 61 36"),
            hex("78 00 5C 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "hasActiveEntitlements",
            hex("30 00 39 02 00 01 14 00 37 01 02 02 BC 54 6C 00 01 53 03 01"),
            hex("78 00 5C 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "useUpgradeToSuper return false",
            hex("32 00 6C 05 02 2A 00 00 05 29"),
            hex("79 00 5C 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "GenerativeUpsellInterstice upsell card",
            hex("32 0C 6C 01 01 37 02 01 01 BD"),
            hex("76 00 5C 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "show paywall screen action",
            hex("32 00 6C 01 01 37 01 01 01 F9"),
            hex("76 00 5C 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "showPaywallScreen selector",
            hex("6C 00 01 36 00 00 01 F8 37 00 00 02 D1 E6"),
            hex("79 00 5C 00 76 00 76 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "ForceUpdateScreen no-op",
            hex("29 08 00 2E 00 08 03 36 00 00 01 79 76 03 51 00 00 03 36 0A 00 02 62 2E 00 08 08 51"),
            hex("76 00 5C 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00 76 00")
        )

        bytes.replaceUnique(
            "presentSuperwall bypass",
            hex("92 12 05 29 02 00 2E 03"),
            hex("8E 12 76 00 76 00 76 00")
        )
        bundle.writeBytes(bytes.withUpdatedSha1())
    }
}

private val hermesMagic = byteArrayOf(0xC6.toByte(), 0x1F, 0xBC.toByte(), 0x03)

private fun ByteArray.requireHermes(path: String) {
    if (size < 12 || !copyOfRange(0, hermesMagic.size).contentEquals(hermesMagic)) {
        throw PatchException("Invalid Hermes bytecode bundle: $path")
    }
}

private fun ByteArray.withUpdatedSha1(): ByteArray {
    val content = dropLast(20).toByteArray()
    return content + MessageDigest.getInstance("SHA-1").digest(content)
}

private fun ByteArray.replaceUnique(name: String, pattern: ByteArray, replacement: ByteArray) {
    if (pattern.size != replacement.size) {
        throw PatchException("BoldVoice $name replacement size mismatch.")
    }
    val offset = indexOf(pattern)
    if (offset < 0) throw PatchException("BoldVoice $name pattern not found.")
    if (indexOf(pattern, offset + 1) >= 0) throw PatchException("BoldVoice $name pattern is not unique.")
    replacement.copyInto(this, offset)
}

private fun ByteArray.indexOf(pattern: ByteArray, start: Int = 0): Int {
    if (pattern.isEmpty() || pattern.size > size) return -1
    val last = size - pattern.size
    outer@ for (offset in start..last) {
        for (index in pattern.indices) {
            if (this[offset + index] != pattern[index]) continue@outer
        }
        return offset
    }
    return -1
}

private fun hex(value: String): ByteArray =
    value.trim().split(Regex("\\s+")).filter(String::isNotEmpty)
        .map { it.toInt(16).toByte() }
        .toByteArray()
